name: kubefarm
description: Kubefarm cluster
version: 0.1.0
appVersion: 5.8.5
keywords:
  - kubernetes
  - ltsp
home: https://github.com/kvaps/kubefarm
sources:
  - https://github.com/kvaps/kubefarm
maintainers:
  - name: kvaps
    email: kvapss@gmail.com
