name: kubefarm
description: Kubefarm cluster
version: 0.2.0
appVersion: 1.18.6
keywords:
  - kubernetes
  - ltsp
home: https://github.com/kvaps/kubefarm
sources:
  - https://github.com/kvaps/kubefarm
maintainers:
  - name: kvaps
    email: kvapss@gmail.com
