name: kubefarm
description: Kubefarm cluster
version: 0.3.1
appVersion: 1.19.0
keywords:
  - kubernetes
  - ltsp
home: https://github.com/kvaps/kubefarm
sources:
  - https://github.com/kvaps/kubefarm
maintainers:
  - name: kvaps
    email: kvapss@gmail.com
