apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cluster1-kubernetes-create-token
        spec:
          containers:
          - name: kubeadm
            image: docker.io/kvaps/kubernetes-tools:v0.0.1
            command:
            - /bin/sh
            - -c
            - |
                kubeadm --kubeconfig /etc/kubernetes/admin.conf token create --description kubefarm --print-join-command > /tmp/token &&
                kubectl patch secret test -p="{\"data\":{\"token\":\"$(cat /tmp/token | base64 | tr -d '\n')\"}}"
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/kubernetes/
              name: kubeconfig
              readOnly: true
    
          restartPolicy: OnFailure
          serviceAccountName: token-generator
          volumes:
          - name: kubeconfig
            secret:
              defaultMode: 420
              secretName: cluster1-kubernetes-admin-conf
