{{- if and .Values.ltsp.enabled .Values.ltsp.service.enabled }}
{{- $fullName := include "ltsp.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if not (index .Values.ltsp.service.annotations "metallb.universe.tf/allow-shared-ip") }}
    metallb.universe.tf/allow-shared-ip: {{ $fullName }}
    {{- end }}
    {{- with .Values.ltsp.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ $fullName }}
  name: {{ $fullName }}-http
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: {{ $fullName }}
  type: {{ .Values.ltsp.service.type }}
  {{- with .Values.ltsp.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if not (index .Values.ltsp.service.annotations "metallb.universe.tf/allow-shared-ip") }}
    metallb.universe.tf/allow-shared-ip: {{ $fullName }}
    {{- end }}
    {{- with .Values.ltsp.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ $fullName }}
  name: {{ $fullName }}-tftp
spec:
  ports:
  - name: tftp
    port: 69
    protocol: UDP
  selector:
    app: {{ $fullName }}
  type: {{ .Values.ltsp.service.type }}
  {{- with .Values.ltsp.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
{{- end }}
