{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations: {}
  labels:
    app: {{ $fullName }}-ltsp-publisher
  name: {{ $fullName }}-ltsp-publish
spec:
  template:
    metadata:
      labels:
        app: {{ $fullName }}-ltsp-publisher
    spec:
      containers:
      - name: kubeadm
        image: docker.io/kvaps/kubernetes-tools:v0.0.1
        command: [ '/scripts/publiship.sh' ]
        env:
        - name: SVC1
          value: {{ $fullName }}-ltsp-tftp
        - name: SVC2
          value: {{ $fullName }}-ltsp-http
        - name: TAG
          value: {{ $fullName }}
        - name: DHCPOPTIONS
          value: {{ $fullName }}-ltsp-ip
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      volumes:
      - name: scripts
        configMap:
          name: {{ $fullName }}-ltsp-scripts
          defaultMode: 0777
      restartPolicy: OnFailure
      serviceAccountName: {{ $fullName }}-ltsp-publisher
