{{- if or .Values.tokenGenerator.enabled (and .Values.ltsp.enabled .Values.ltsp.publishDHCP) }}
{{- $fullName := include "ltsp.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: {{ $fullName }}
  name: {{ $fullName }}-scripts
data:
  {{- if .Values.tokenGenerator.enabled }}
  gentoken.sh: |+
    {{- .Files.Get "scripts/gentoken.sh" | nindent 4 }}
  {{- end }}

  {{- if and .Values.ltsp.enabled .Values.ltsp.publishDHCP (not .Values.ltsp.service.loadBalancerIP) }}
  publiship.sh: |+
    {{- .Files.Get "scripts/publiship.sh" | nindent 4 }}
  {{- end }}
{{- end }}
