{{- if .Values.tokenGenerator.enabled }}
{{- $fullName := include "ltsp.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  annotations: {}
  labels:
    app: {{ $fullName }}-join-token
  name: {{ $fullName }}-join-token
{{- end }}
