{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if not (index .Values.ltsp.service.annotations "metallb.universe.tf/allow-shared-ip") }}
    metallb.universe.tf/allow-shared-ip: {{ $fullName }}
    {{- end }}
    {{- with .Values.ltsp.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ $fullName }}-ltsp
  name: {{ $fullName }}-ltsp-http
spec:
  #loadBalancerIP: 1.2.3.4
  ports:
  - name: http
    port: 80
  selector:
    app: ltsp1
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if not (index .Values.ltsp.service.annotations "metallb.universe.tf/allow-shared-ip") }}
    metallb.universe.tf/allow-shared-ip: {{ $fullName }}
    {{- end }}
    {{- with .Values.ltsp.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ $fullName }}-ltsp
  name: {{ $fullName }}-ltsp-tftp
spec:
  #loadBalancerIP: 1.2.3.4
  ports:
  - name: tftp
    port: 69
    protocol: UDP
  selector:
    app: {{ $fullName }}-ltsp
  type: LoadBalancer
