{{- if and .Values.ltsp.enabled .Values.ltsp.publishDHCP (not .Values.ltsp.service.loadBalancerIP) }}
{{- $fullName := include "ltsp.fullname" . -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app: {{ $fullName }}-publisher
  name: {{ $fullName }}-publish
spec:
  template:
    metadata:
      labels:
        app: {{ $fullName }}-publisher
    spec:
      {{- with .Values.kubernetes.admin.image.PullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      containers:
      - name: kubeadm
        image: {{ .Values.kubernetes.admin.image.repository }}:{{ .Values.kubernetes.admin.image.tag }}
        imagePullPolicy: {{ .Values.kubernetes.admin.image.PullPolicy }}
        command: [ '/scripts/publiship.sh' ]
        env:
        - name: SVC1
          value: {{ $fullName }}-tftp
        - name: SVC2
          value: {{ $fullName }}-http
        - name: TAG
          value: {{ $fullName }}
        - name: DHCPOPTIONS
          value: {{ $fullName }}-ip
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      volumes:
      - name: scripts
        configMap:
          name: {{ $fullName }}-scripts
          defaultMode: 0777
      restartPolicy: OnFailure
      serviceAccountName: {{ $fullName }}-publisher
{{- end }}
