{{- $fullName := include "ltsp.fullname" . -}}
{{- $hasTags := false -}}
{{- range $key, $values := .Values.tags.dhcpOptions }}
{{- if $values }}
{{- $hasTags = true -}}
{{- end }}
{{- end }}

{{- if $hasTags }}
{{- with .Values.tags.dhcpOptions }}
---
apiVersion: dnsmasq.kvaps.cf/v1beta1
kind: DhcpOptions
metadata:
  annotations: {}
  labels:
    app: {{ $fullName }}
  name: {{ $fullName }}-tags
spec:
  controller: ""
  options:
  {{- range $tag, $options := . }}
    {{- range $key, $values := $options }}
    - key: "{{ template "kubefarm.dhcpOptionKey" $key }}"
      tags:
        - {{ $fullName | quote }}
        {{- if not (eq $tag "all") }}
        - {{ $tag | quote }}
        {{- end }}
      values:
        {{- range $k, $v := split "," $values }}
        - {{ $v | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
