{{- $fullName := include "ltsp.fullname" . -}}
---
apiVersion: dnsmasq.kvaps.cf/v1beta1
kind: DhcpOptions
metadata:
  annotations: {}
  labels:
    app: {{ $fullName }}
  name: {{ $fullName }}-ip
spec:
  controller: ""
