---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {}
  labels:
  name: ltsp1-config
data:
  authorized_keys: |
    {{- join "\n" .Values.ltsp.config.sshAuthorizedKeys | nindent 4 }}
  docker.json: |
    {{- toPrettyJson .Values.ltsp.config.dockerConfig | nindent 4 }}
  kubeadm-join.service: |
    [Unit]
    Description=Join Kubernetes
    After=network-online.target
    Wants=network-online.target
    Wants=docker.service docker.socket
    After=docker.service docker.socket

    [Service]
    Type=oneshot
    ExecStart=/usr/bin/kubeadm join cluster1-kubernetes-apiserver:6443 --token bupcga.nye4j4f9187uclsf     --discovery-token-ca-cert-hash sha256:d4df307e8c9a978d1a70d241edb867c8ef71c06cb84cb8e2bb6f7c6eb51201ae
    Restart=on-failure

    [Install]
    WantedBy=multi-user.target
  ltsp.conf: |
    [common]
    {{- range $k, $v := .Values.ltsp.config.options }}
    {{ $k }}={{ $v | quote }}
    {{- end }}

    [init/]
    {{- with .Values.ltsp.config.disableAutoupdate }}
    # Disable autoupdates
    systemctl mask apt-daily.timer apt-daily-upgrade.timer
    {{- end }}

    {{- with .Values.ltsp.config.timezone }}
    # Set timezone
    ln -sf /usr/share/zoneinfo/{{ . }} /etc/localtime
    {{- end }}

    # Setup SSH Daemon
    ssh-keygen -A

    {{- with .Values.ltsp.config.sysctls }}
    # Sysctl settings
    cp -f /etc/ltsp/sysctl.conf /etc/sysctl.d/99-sysctl.conf
    {{- end }}

    {{- with .Values.ltsp.config.rootPasswd }}
    # Setup root account
    usermod -p '$1$UtII3YsI$lN5uWqKWmABh9lb5LOw6m0' root
    sed -i 's/#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
    {{- end }}

    # TODO

    {{- with index .Values.ltsp.config.sections "init/" }}
    {{- . | nindent 4 }}
    {{- end }}

    {{- range $k, $v := .Values.ltsp.config.sections }}
    {{- if not (eq $k "init/") }}
    [{{ $k }}]
    {{- $v | nindent 4 }}
    {{- end }}
    {{- end }}

    {{- /* transpose .Values.tags to $tags */}}
    {{- $tags := dict }}
    {{- range $opt, $tag := .Values.tags }}
    {{- range $tag, $vals := $tag }}
    {{- $opts := get $tags $tag | default dict }}
    {{- $_ := set $opts $opt $vals}}
    {{- $_ := set $tags $tag $opts}}
    {{- end }}
    {{- end }}

    # Options
    {{- with $tags }}
    {{- range $t, $v := $tags }}
    {{- if eq $t "all" }}
    [clients]
    {{- else }}
    [tag_{{ $t }}]
    {{- end }}
    {{- range $k, $v := $v.ltspOptions }}
    {{ $k }}={{ $v | quote }}
    {{- end }}
    {{- with $v.kubernetesLabels }}
    KUBERNETES_LABELS_{{ regexReplaceAll "\\W+" ($t | upper) "_" }}={{ (include "kubefarm.kubernetesLabels" .) | quote }}
    {{- end }}
    {{- with $v.kubernetesTaints }}
    KUBERNETES_TAINTS_{{ regexReplaceAll "\\W+" ($t | upper) "_" }}={{ (include "kubefarm.kubernetesTaints" .) | quote }}
    {{- end }}
    {{- end }}
    {{- end }}

    # Nodes
    {{- range $p := .Values.nodePools }}
    {{- range $n := $p.nodes }}
    {{- if $n.mac }}
    [{{ $n.mac }}]
    {{- else if $.ip }}
    [{{ $n.ip }}]
    {{- else }}
    [{{ $n.name }}]
    {{- end }}
    {{- range $t := $p.tags }}
    INCLIDE={{ printf "tag_%s" $t | quote }}
    {{- end }}
    {{- end }}
    {{- end }}

  modules: |
    {{- join "\n" .Values.ltsp.config.modules | nindent 4 }}

  sysctl.conf: |
    {{- range $k, $v := .Values.ltsp.config.sysctls }}
    {{ $k }}={{ $v }}
    {{- end }}
