{{- $fullName := include "kubernetes.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  annotations: {}
  labels:
    app: {{ $fullName }}-ltsp-join-token
  name: {{ $fullName }}-ltsp-join-token
