{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations: {}
  labels:
    app: {{ $fullName }}-token-generator
  name: {{ $fullName }}-token-generator
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - watch
  resourceNames:
  - {{ $fullName }}-apiserver
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - patch
  resourceNames:
  - {{ $fullName }}-ltsp-join-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app: {{ $fullName }}-token-generator
  name: {{ $fullName }}-token-generator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations: {}
  labels:
    app: {{ $fullName }}-token-generator
  name: {{ $fullName }}-token-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-token-generator
subjects:
- kind: ServiceAccount
  name: {{ $fullName }}-token-generator
  namespace: {{ .Release.Namespace }}
